CREATE TABLE `mm_custom_info` (
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '客户编号',
`phone` varchar(20) NULL COMMENT '电话',
`name` varchar(255) NULL COMMENT '客户姓名',
`gender` varchar(20) NULL COMMENT '性别',
`birthday` date NULL COMMENT '出生日期',
`email` varchar(255) NULL DEFAULT '' COMMENT '电子邮箱',
`address` varchar(255) NULL COMMENT '地址',
`id_number` varchar(20) NULL COMMENT '身份证号码',
`profession` varchar(255) NULL COMMENT '职业',
`introducer_phone` varchar(20) NULL COMMENT '推荐人电话',
`introducer_name` varchar(128) NULL COMMENT '推荐人姓名',
`membership_grade` varchar(255) NULL COMMENT '会员等级',
`membership_point` int NULL DEFAULT 0 COMMENT '会员积分',
`recent_consume_time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '最近消费时间',
`balance` decimal NULL DEFAULT 0 COMMENT '余额',
`total_consume` decimal NULL DEFAULT 0 COMMENT '累计消费',
`status` varchar(20) NULL DEFAULT '' COMMENT '状态',
`regist_time` date NULL DEFAULT NULL COMMENT '注册时间',
`image_url` varchar(255) NULL DEFAULT '' COMMENT '照片url',
`remarks` varchar(255) NULL DEFAULT '' COMMENT '备注信息',
`del_flag` tinyint NULL DEFAULT NULL COMMENT '用户删除标记 0:未删除 1:已删除',
`update_Time` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`attachment_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_order_base` (
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单编号',
`consult_time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '咨询时间',
`book_time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '预约时间',
`counselor_name` varchar(20) NULL COMMENT '咨询师姓名',
`custom_phone` varchar(20) NULL COMMENT '客户电话',
`is_first` tinyint NULL COMMENT '是否首次到院',
`origin_custom_comeback` tinyint NULL DEFAULT 0 COMMENT '顾客回头',
`origin_custom_introduce` tinyint NULL DEFAULT 0 COMMENT '顾客介绍',
`origin_advertisement` tinyint NULL DEFAULT 0 COMMENT '广告',
`origin_wechat` tinyint NULL DEFAULT 0 COMMENT '微信',
`origin_sms` tinyint NULL DEFAULT 0 COMMENT '短信',
`origin_self` tinyint NULL DEFAULT 0 COMMENT '自行到店',
`origin_other` tinyint NULL DEFAULT 0 COMMENT '其他',
`introducer_phone` varchar(128) NULL DEFAULT NULL COMMENT '介绍人电话',
`introducer_name` varchar(255) NULL DEFAULT NULL COMMENT '介绍人姓名',
`introducer_points_syn` tinyint NULL DEFAULT 0 COMMENT '介绍人积分同步状态',
`rebate_amount` decimal NULL COMMENT '合作伙伴返利金额',
`project_requirement_eyebrow` tinyint NULL DEFAULT 0 COMMENT '眉毛',
`project_requirement_lip` tinyint NULL DEFAULT 0 COMMENT '唇',
`project_requirement_eyeliner` tinyint NULL DEFAULT 0 COMMENT '眼线',
`project_requirement_hairline` tinyint NULL DEFAULT 0 COMMENT '发际线',
`project_requirement_tattoo` tinyint NULL DEFAULT 0 COMMENT '文身',
`project_requirement_wash` tinyint NULL DEFAULT 0 COMMENT '洗眉/唇/眼线/文身',
`healthy_status` varchar(255) NULL DEFAULT '' COMMENT '健康状况',
`allergic_history` varchar(255) NULL DEFAULT '' COMMENT '过敏史',
`temperature` double NULL DEFAULT NULL COMMENT '体温(摄氏度)',
`pulse` int(11) NULL DEFAULT NULL COMMENT '脉搏(次/分)',
`blood_pressure` varchar(128) NULL DEFAULT NULL COMMENT '血压(mmHg)',
`medical_history_1` tinyint NULL DEFAULT 0 COMMENT '治疗区感染/过敏',
`medical_history_2` tinyint NULL DEFAULT 0 COMMENT '出血性疾病',
`medical_history_3` tinyint NULL DEFAULT 0 COMMENT '心脑血疾病',
`medical_history_4` tinyint NULL DEFAULT 0 COMMENT '眼病',
`medical_history_5` tinyint NULL DEFAULT 0 COMMENT '传染病',
`medical_history_6` tinyint NULL DEFAULT 0 COMMENT '糖尿病',
`medical_history_7` tinyint NULL DEFAULT 0 COMMENT '高血压',
`medical_history_8` tinyint NULL DEFAULT 0 COMMENT '其它',
`medical_history_dose` varchar(255) NULL DEFAULT '' COMMENT '以上疾病情况及用药',
`last_menstruation` date NULL DEFAULT NULL COMMENT '末次月经时间',
`cosmetology_history` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '既往美容治疗史',
`cosmetology_base_condition` varchar(255) NULL DEFAULT '' COMMENT '美容基础条件',
`counselor_suggest` varchar(255) NULL DEFAULT '' COMMENT '咨询医师建议',
`receivable_total` decimal NULL COMMENT '应收合计',
`received_total` decimal NULL COMMENT '实收合计',
`cashier_name` varchar(20) NULL COMMENT '收银员姓名',
`payment_time` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '支付时间',
`payment_mode` varchar(255) NULL COMMENT '支付方式',
`payment_status` tinyint NULL DEFAULT 0 COMMENT '支付状态',
`remarks` varchar(255) NULL DEFAULT '' COMMENT '备注',
`revisit_days` int NULL COMMENT '回访周期(天)',
`revisit_datetime` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '回访日期',
`revisit_flag` tinyint NULL COMMENT '回访标志',
`del_flag` tinyint NULL COMMENT '用户删除标记 0:未删除 1:已删除',
`update_Time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
`attachment_id` varchar(128) NULL,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_order_detail` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`order_id` int NULL COMMENT '订单编号',
`good_code` varchar(128) NULL COMMENT '商品编码或套餐编码(1开头为商品，2开头为套餐）',
`setmeal_code` varchar(128) NULL COMMENT '所属套餐（“-1”独立商品）',
`maintenance_end_date` date NULL DEFAULT 0 COMMENT '维保期终止日期',
`operation_doctor_name` varchar(20) NULL COMMENT '操作医师姓名',
`operation_datetime` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间',
`receivable` decimal NULL COMMENT '应收',
`received` decimal NULL COMMENT '实收',
`points` double NULL COMMENT '积分',
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_goods_info` (
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品id',
`goods_type` varchar(128) NULL COMMENT '商品类型',
`goods_code` varchar(128) NULL COMMENT '商品编码',
`goods_name` varchar(255) NULL COMMENT '商品名称',
`goods_classify` varchar(128) NULL COMMENT '商品分类',
`price` decimal NULL COMMENT '商品售价',
`goods_simplecode` varchar(128) NULL COMMENT '商品简码',
`reference_price` decimal NULL COMMENT '参考进价',
`specifications` varchar(255) NULL COMMENT '规格型号',
`brand` varchar(255) NULL COMMENT '品牌',
`stock` int(255) NULL COMMENT '库存',
`unit` varchar(128) NULL COMMENT '计量单位',
`is_discount` tinyint NULL DEFAULT 0 COMMENT '是否折扣',
`min_discount` double NULL COMMENT '最低折扣',
`special_discount` double(255,0) NULL COMMENT '特价折扣',
`points_rule` varchar(128) NULL COMMENT '积分规则',
`fixed_points` int(255) NULL COMMENT '固定积分',
`maintenance_period` int NULL COMMENT '维保期(天)',
`del_flag` tinyint NULL COMMENT '用户删除标记 0:未删除 1:已删除',
`update_Time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
`attachment_id` varchar(128) NULL,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_setmeal_base` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`setmeal_type` varchar(255) NULL COMMENT '套餐类型',
`setmeal_code` varchar(128) NULL COMMENT '套餐编号',
`setmeal_name` varchar(255) NULL COMMENT '套餐名称',
`price` decimal NULL COMMENT '套餐价格',
`discount` varchar(255) NULL COMMENT '折扣',
`setmeal_points` int NULL COMMENT '套餐积分',
`setmeal_specifications` varchar(255) NULL COMMENT '套餐规格',
`remarks` varchar(255) NULL COMMENT '备注',
`del_flag` tinyint(255) NULL,
`update_Time` datetime NULL ON UPDATE CURRENT_TIMESTAMP,
`attachment_id` varchar(128) NULL,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_setmeal_detail` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`setmeal__code` varchar(128) NULL COMMENT '套餐编码',
`goods_code` varchar(128) NULL COMMENT '商品编码',
`price` decimal NULL COMMENT '套餐中商品价格',
`del_flag` tinyint(1) NULL COMMENT '用户删除标记 0:未删除 1:已删除',
`update_Time` datetime NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_membership_grade` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`membership_grade` varchar(128) NULL COMMENT '积分等级',
`points_ratio` double NULL DEFAULT 1 COMMENT '积分系数',
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_cooperative` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`cooperative_type` varchar(128) NULL COMMENT '合作伙伴类型',
`cooperative_name` varchar(128) NULL COMMENT '合作伙伴名称',
`contact_phone` varchar(20) NULL COMMENT '联系人电话',
`contact_name` varchar(20) NULL COMMENT '联系人姓名',
`discount` double NULL COMMENT '优惠',
`rebate_ratio` double NULL COMMENT '返利比例',
`fixed_rebate` decimal NULL COMMENT '固定返利',
`wechat` varchar(128) NULL COMMENT '微信',
`zhifubao` varchar(128) NULL,
`bank_card` varchar(128) NULL,
`bank_of_deposit` varchar(128) NULL COMMENT '开户行',
`total_rebate` decimal NULL COMMENT '累计返利',
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_bespeak_base` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`custom_phone` varchar(20) NULL COMMENT '客户电话',
`bespeak_money` decimal NULL COMMENT '预付金额',
`bespeak_time` datetime NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '预约时间',
`time_limit` int NULL COMMENT '有效期(小时)',
`doctor_name` varchar(20) NULL COMMENT '预约医师',
`项目_补` varchar(255) NULL,
PRIMARY KEY (`id`) 
);
CREATE TABLE `mm_bespeak_detail` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`bespeak_id` int(11) NULL COMMENT '客户电话',
`gcode` varchar(128) NULL COMMENT '预约商品编码',
`scode` varchar(128) NULL COMMENT '预约套餐编码',
`bespeak_price` decimal NULL COMMENT '预约价格',
`remarks` varchar(255) NULL COMMENT '备注',
PRIMARY KEY (`id`) 
);

